# Generated by Django 5.0.6 on 2024-07-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
